import { useCallback, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { ethers } from "ethers";
import { Edit3, Eye, Link2, Loader2, Package, Plus, RefreshCw, Search, Send, Truck, UserCog, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useWallet } from "@/hooks/use-wallet";
import { useSihContext } from "@/hooks/use-sih";
import { ensureSepolia, getAssetNFT, getCredentialAssetBridge, getInjectedProvider, isSihPlatformConfigured } from "@/lib/contract";
import { describeError } from "@/lib/issuance";
import { ASSET_TYPES, assetStatusLabel, assetTypeLabel, fetchAssetHistory, fetchAssets, type AssetRecord } from "@/lib/sih-assets";
import { AddressChip } from "@/components/data/AddressChip";
import { cn } from "@/lib/utils";

const statusClass = (status: number) => status === 1 ? "bg-success/15 text-success border-success/30" : status === 2 ? "bg-blue/15 text-blue border-blue/30" : status >= 3 ? "bg-warning/15 text-warning border-warning/30" : "bg-muted text-muted-foreground border-border";

export default function ManagerDashboard() {
  const { toast } = useToast(); const { address } = useWallet(null); const { identity, role, loading: roleLoading } = useSihContext(null);
  const [assets, setAssets] = useState<AssetRecord[]>([]); const [selected, setSelected] = useState<AssetRecord | null>(null); const [history, setHistory] = useState<Awaited<ReturnType<typeof fetchAssetHistory>>>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [search, setSearch] = useState(""); const [typeFilter, setTypeFilter] = useState("all"); const [showMint, setShowMint] = useState(false); const [action, setAction] = useState<"assign" | "transfer" | "metadata" | "link" | null>(null);
  const [form, setForm] = useState({ type: "0", owner: "", assignee: "", did: "", uri: "", to: "", credentialHash: "" });
  const load = useCallback(async () => { if (!isSihPlatformConfigured() || !address) return; setLoading(true); try { setAssets(await fetchAssets()); } catch (error) { toast({ title: "Could not load assets", description: describeError(error), variant: "destructive" }); } finally { setLoading(false); } }, [address, toast]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => assets.filter((asset) => { const q = search.toLowerCase(); return (typeFilter === "all" || asset.assetType.toString() === typeFilter) && (!q || [asset.tokenId, asset.owner, asset.assignee, asset.did, asset.metadataURI].some((v) => v.toLowerCase().includes(q))); }), [assets, search, typeFilter]);
  const execute = async (fn: (signer: ethers.Signer) => Promise<ethers.TransactionResponse>) => { setBusy(true); try { await ensureSepolia(); const provider = new ethers.BrowserProvider(getInjectedProvider()!); const tx = await fn(await provider.getSigner()); toast({ title: "Transaction submitted", description: `${tx.hash.slice(0, 10)}…` }); await tx.wait(); toast({ title: "Blockchain updated", description: "The asset record is confirmed." }); setAction(null); setShowMint(false); setForm({ type: "0", owner: "", assignee: "", did: "", uri: "", to: "", credentialHash: "" }); await load(); } catch (error) { toast({ title: "Transaction rejected", description: describeError(error), variant: "destructive" }); } finally { setBusy(false); } };
  const mint = () => execute(async (signer) => { const owner = form.owner || address!; const assignee = form.assignee || owner; if (!ethers.isAddress(owner) || !ethers.isAddress(assignee) || !form.uri.trim()) throw new Error("Owner, assignee, and metadata URI are required."); return getAssetNFT(signer).mintAsset(Number(form.type), owner, assignee, form.did.trim(), form.uri.trim()); });
  const submitAction = () => { if (!selected) return; if (action === "assign") return execute((signer) => getAssetNFT(signer).assignAsset(selected.tokenId, form.to)); if (action === "transfer") return execute((signer) => getAssetNFT(signer).transferOwnership(selected.tokenId, form.to)); if (action === "link") return execute((signer) => getCredentialAssetBridge(signer).linkAssetToCredential(selected.tokenId, form.owner || selected.owner, form.credentialHash)); return execute((signer) => getAssetNFT(signer).updateMetadataURI(selected.tokenId, form.uri)); };
  const openDetails = async (asset: AssetRecord) => { setSelected(asset); setHistory(await fetchAssetHistory(asset.tokenId)); };
  if (!address) return <Empty title="Connect wallet" text="Connect the manager wallet to manage blockchain assets." />;
  if (roleLoading || loading) return <div className="mx-auto max-w-7xl px-4 py-20 text-center text-muted-foreground"><Loader2 className="mx-auto h-6 w-6 animate-spin" /><p className="mt-3">Reading asset registry…</p></div>;
  if (!role.isAtLeastManager) return <Empty title="Access denied" text={`Your on-chain role is ${role.role}. Asset writes require the Manager role.`} />;
  return <div className="mx-auto max-w-7xl px-4 py-8"><header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg border bg-muted"><UserCog className="h-5 w-5 text-primary" /></span><div><h1 className="text-xl font-semibold">Asset operations</h1><div className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><AddressChip address={address} size="sm" />{identity?.name && <span>{identity.name}</span>}<span className="rounded-full border border-primary/30 bg-primary/10 px-2 py-0.5 text-xs text-primary">Manager</span></div></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load()}><RefreshCw className="h-4 w-4" /> Refresh</Button><Button onClick={() => setShowMint(true)}><Plus className="h-4 w-4" /> Create asset</Button></div></header>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Assets on chain" value={assets.length} /><Metric label="Assigned" value={assets.filter((a) => a.assignee !== ethers.ZeroAddress).length} /><Metric label="Active" value={assets.filter((a) => a.status === 1).length} /></div>
    <section className="mt-6 overflow-hidden rounded-lg border bg-card"><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search token, wallet, DID or URI" value={search} onChange={(e) => setSearch(e.target.value)} /></div><Select value={typeFilter} onValueChange={setTypeFilter}><SelectTrigger className="w-44"><SelectValue placeholder="All asset types" /></SelectTrigger><SelectContent><SelectItem value="all">All asset types</SelectItem>{ASSET_TYPES.map((type, i) => <SelectItem key={type} value={i.toString()}>{type}</SelectItem>)}</SelectContent></Select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="p-3">Asset</th><th className="p-3">Status</th><th className="p-3">Owner</th><th className="p-3">Assigned to</th><th className="p-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{visible.map((asset) => <tr key={asset.tokenId} className="hover:bg-muted/30"><td className="p-3"><div className="font-medium">#{asset.tokenId} · {assetTypeLabel(asset.assetType)}</div><div className="mt-1 max-w-[220px] truncate text-xs text-muted-foreground">{asset.metadataURI}</div></td><td className="p-3"><span className={cn("rounded-full border px-2 py-0.5 text-xs", statusClass(asset.status))}>{assetStatusLabel(asset.status)}</span></td><td className="p-3"><AddressChip address={asset.owner} size="sm" /></td><td className="p-3"><AddressChip address={asset.assignee} size="sm" /></td><td className="p-3"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label="View asset" onClick={() => void openDetails(asset)}><Eye className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Assign asset" onClick={() => { setSelected(asset); setAction("assign"); setForm((f) => ({ ...f, to: "" })); }}><Truck className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Transfer asset" onClick={() => { setSelected(asset); setAction("transfer"); setForm((f) => ({ ...f, to: "" })); }}><Send className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Edit metadata" onClick={() => { setSelected(asset); setAction("metadata"); setForm((f) => ({ ...f, uri: asset.metadataURI })); }}><Edit3 className="h-4 w-4" /></Button></div></td></tr>)}{visible.length === 0 && <tr><td colSpan={5} className="p-12 text-center text-muted-foreground">No blockchain assets match this view.</td></tr>}</tbody></table></div></section>
    {(showMint || action) && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-lg border bg-card p-6 shadow-lg"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">{showMint ? "Create asset" : action === "assign" ? "Assign asset" : action === "transfer" ? "Transfer ownership" : "Update metadata"}</h2><p className="mt-1 text-sm text-muted-foreground">Every change is confirmed by AssetNFT.</p></div><Button variant="ghost" size="icon" onClick={() => { setShowMint(false); setAction(null); }}><X className="h-4 w-4" /></Button></div>{showMint ? <div className="mt-5 space-y-4"><Field label="Asset type"><Select value={form.type} onValueChange={(v) => setForm((f) => ({ ...f, type: v }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{ASSET_TYPES.map((type, i) => <SelectItem key={type} value={i.toString()}>{type}</SelectItem>)}</SelectContent></Select></Field><Field label="Owner address"><Input value={form.owner} onChange={(e) => setForm((f) => ({ ...f, owner: e.target.value }))} placeholder={address} /></Field><Field label="Assignee address"><Input value={form.assignee} onChange={(e) => setForm((f) => ({ ...f, assignee: e.target.value }))} placeholder="Defaults to owner" /></Field><Field label="Identity DID (optional)"><Input value={form.did} onChange={(e) => setForm((f) => ({ ...f, did: e.target.value }))} placeholder="did:sih:person-001" /></Field><Field label="Metadata URI"><Input value={form.uri} onChange={(e) => setForm((f) => ({ ...f, uri: e.target.value }))} placeholder="ipfs://…" /></Field><Button className="w-full" disabled={busy} onClick={mint}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : "Mint on chain"}</Button></div> : <div className="mt-5 space-y-4"><p className="rounded-md bg-muted p-3 text-sm">Asset <span className="font-mono">#{selected?.tokenId}</span> · {selected && assetTypeLabel(selected.assetType)}</p>{action !== "metadata" ? <Field label="Destination address"><Input value={form.to} onChange={(e) => setForm((f) => ({ ...f, to: e.target.value }))} placeholder="0x…" /></Field> : <Field label="Metadata URI"><Textarea value={form.uri} onChange={(e) => setForm((f) => ({ ...f, uri: e.target.value }))} rows={3} /></Field>}<Button className="w-full" disabled={busy} onClick={submitAction}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : "Confirm blockchain update"}</Button></div>}</div></div>}
    {selected && !action && !showMint && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={() => setSelected(null)}><div className="w-full max-w-2xl rounded-lg border bg-card p-6" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Asset detail</p><h2 className="mt-1 text-xl font-semibold">#{selected.tokenId} · {assetTypeLabel(selected.assetType)}</h2></div><Button variant="ghost" size="icon" onClick={() => setSelected(null)}><X className="h-4 w-4" /></Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Owner" value={selected.owner} mono /><Info label="Assigned to" value={selected.assignee} mono /><Info label="Identity" value={selected.did || "Not linked"} mono /><Info label="Metadata" value={selected.metadataURI} mono /><Info label="Status" value={assetStatusLabel(selected.status)} /><Info label="Created" value={new Date(selected.createdAt * 1000).toLocaleString()} /></div><h3 className="mt-6 border-t pt-5 text-sm font-semibold">On-chain history</h3><div className="mt-3 space-y-2">{history.length ? history.map((event, i) => <div key={`${event.transactionHash}-${i}`} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3 text-sm"><span>{event.kind.replace("Asset", "Asset ")}</span><span className="font-mono text-xs text-muted-foreground">block {event.blockNumber} · {event.transactionHash.slice(0, 12)}…</span></div>) : <p className="text-sm text-muted-foreground">No events returned for this asset.</p>}</div></div></div>}
  </div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <div><Label className="mb-1.5 block">{label}</Label>{children}</div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border bg-card p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p></div>; }
function Info({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={cn("mt-1 break-all text-sm", mono && "font-mono text-xs")}>{value}</p></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="mx-auto max-w-xl px-4 py-20 text-center"><Package className="mx-auto h-10 w-10 text-muted-foreground" /><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-2 text-muted-foreground">{text}</p></div>; }
