import { useCallback, useEffect, useMemo, useState } from "react";
import { ExternalLink, FileCheck2, History, LayoutDashboard, Loader2, Package, RefreshCw, User, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { useWallet } from "@/hooks/use-wallet";
import { useSihContext } from "@/hooks/use-sih";
import { fetchCredentialsForHolder, type CredentialRecord } from "@/lib/credentials";
import { fetchAssetHistory, fetchAssets, assetStatusLabel, assetTypeLabel, type AssetRecord } from "@/lib/sih-assets";
import { getCredentialAssetBridgeRO, isSihPlatformConfigured } from "@/lib/contract";
import { describeError } from "@/lib/issuance";
import { AddressChip } from "@/components/data/AddressChip";
import { HashDisplay } from "@/components/data/HashDisplay";
import { cn } from "@/lib/utils";

export default function UserDashboard() {
  const { toast } = useToast(); const { address } = useWallet("sih"); const { identity, role, loading: roleLoading } = useSihContext("sih");
  const [assets, setAssets] = useState<AssetRecord[]>([]); const [credentials, setCredentials] = useState<CredentialRecord[]>([]); const [credentialAssets, setCredentialAssets] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<AssetRecord | null>(null); const [history, setHistory] = useState<Awaited<ReturnType<typeof fetchAssetHistory>>>([]);
  const load = useCallback(async () => { if (!address || !isSihPlatformConfigured()) return; setLoading(true); try { const all = await fetchAssets(); setAssets(all.filter((a) => a.owner.toLowerCase() === address.toLowerCase() || a.assignee.toLowerCase() === address.toLowerCase())); try { const loadedCredentials = await fetchCredentialsForHolder(address); setCredentials(loadedCredentials); const bridge = getCredentialAssetBridgeRO(); const linked = await Promise.all(loadedCredentials.map(async (credential) => [credential.documentHash, await bridge.isCredentialLinked(credential.documentHash) ? (await bridge.getAssetForCredential(credential.documentHash)).toString() : ""] as const)); setCredentialAssets(Object.fromEntries(linked.filter(([, tokenId]) => tokenId))); } catch (error) { console.warn("Credential history unavailable", error); } } catch (error) { toast({ title: "Could not load your assets", description: describeError(error), variant: "destructive" }); } finally { setLoading(false); } }, [address, toast]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => assets.filter((a) => !search || [a.tokenId, a.metadataURI, a.did, a.owner, a.assignee].some((v) => v.toLowerCase().includes(search.toLowerCase()))), [assets, search]);
  if (!address) return <Empty title="Connect wallet" text="Connect your wallet to view the identity and assets controlled by it." />;
  if (roleLoading || loading) return <div className="mx-auto max-w-7xl px-4 py-20 text-center text-muted-foreground"><Loader2 className="mx-auto h-6 w-6 animate-spin" /><p className="mt-3">Reading your identity and assets…</p></div>;
  return <div className="mx-auto max-w-7xl px-4 py-8"><header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg border bg-muted"><LayoutDashboard className="h-5 w-5 text-primary" /></span><div><h1 className="text-xl font-semibold">My digital identity</h1><div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><AddressChip address={address} size="sm" />{identity?.name && <span>{identity.name}</span>}<span className="rounded-full border px-2 py-0.5 text-xs capitalize">{role.role}</span></div></div></div><Button variant="outline" onClick={() => void load()}><RefreshCw className="h-4 w-4" /> Refresh</Button></header>
    <div className="mt-8 grid gap-4 sm:grid-cols-4"><Metric label="Owned" value={assets.filter((a) => a.owner.toLowerCase() === address.toLowerCase()).length} /><Metric label="Assigned" value={assets.filter((a) => a.assignee.toLowerCase() === address.toLowerCase()).length} /><Metric label="Documents" value={credentials.length} /><Metric label="Linked assets" value={Object.keys(credentialAssets).length} /></div>
    <Tabs defaultValue="assets" className="mt-6"><TabsList><TabsTrigger value="assets"><Package className="h-4 w-4" /> Assets</TabsTrigger><TabsTrigger value="documents"><FileCheck2 className="h-4 w-4" /> Certificates & documents</TabsTrigger><TabsTrigger value="identity"><User className="h-4 w-4" /> Identity</TabsTrigger></TabsList>
      <TabsContent value="assets" className="mt-5"><div className="rounded-lg border bg-card"><div className="border-b p-4"><Input placeholder="Search your assets" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="grid gap-3 p-4 md:grid-cols-2">{visible.map((asset) => <button key={asset.tokenId} className="rounded-lg border p-4 text-left transition hover:border-primary/50 hover:bg-muted/30" onClick={async () => { setSelected(asset); setHistory(await fetchAssetHistory(asset.tokenId)); }}><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">Asset #{asset.tokenId}</p><h3 className="mt-1 font-medium">{assetTypeLabel(asset.assetType)}</h3></div><span className="rounded-full border px-2 py-0.5 text-xs">{assetStatusLabel(asset.status)}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Info label="Owner" value={asset.owner} mono /><Info label="Assignment" value={asset.assignee} mono /><Info label="Identity" value={asset.did || "Not linked"} mono /><Info label="Metadata" value={asset.metadataURI} mono /></div></button>)}{visible.length === 0 && <p className="p-10 text-center text-sm text-muted-foreground">No assets are owned or assigned to this wallet yet.</p>}</div></div></TabsContent>
      <TabsContent value="documents" className="mt-5"><div className="space-y-3">{credentials.map((credential) => <div key={credential.documentHash} className="rounded-lg border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-success" /><h3 className="font-medium">{credential.metadata?.title || "Verified document"}</h3><span className={cn("rounded-full border px-2 py-0.5 text-xs", credential.isValid && !credential.isExpired ? "border-success/30 bg-success/10 text-success" : "border-warning/30 bg-warning/10 text-warning")}>{credential.isValid && !credential.isExpired ? "Verified" : "Needs review"}</span></div><p className="mt-2 text-sm text-muted-foreground">Issued by {credential.issuerName} · {credential.issuedAt.toLocaleDateString()}</p></div><Button variant="outline" size="sm" asChild><a href={`/#/verify?holder=${credential.holder}&hash=${credential.documentHash}`}><ExternalLink className="h-4 w-4" /> Verify</a></Button></div><div className="mt-3"><HashDisplay value={credential.documentHash} lead={10} tail={8} /></div></div>)}{credentials.length === 0 && <Empty title="No documents yet" text="Certificates issued to this wallet will appear here after the chain confirms them." />}</div></TabsContent>
      <TabsContent value="identity" className="mt-5"><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><User className="h-4 w-4" /> Identity record</h2>{identity ? <div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Name" value={identity.name} /><Info label="Email" value={identity.email || "Not supplied"} /><Info label="DID" value={identity.did || "—"} mono /><Info label="Role" value={role.role} /><Info label="KYC" value={identity.kycStatus === 2 ? "Verified" : identity.kycStatus === 1 ? "Pending" : "Not verified"} /><Info label="Status" value={identity.isActive ? "Active" : "Inactive"} /><div className="sm:col-span-2"><p className="text-xs text-muted-foreground">Linked wallets</p><div className="mt-2 flex flex-wrap gap-2">{identity.wallets.map((wallet) => <AddressChip key={wallet} address={wallet} size="sm" showCopy={false} />)}</div></div></div> : <p className="mt-4 text-sm text-muted-foreground">This wallet is not registered in the IdentityRegistry.</p>}</section><section className="rounded-lg border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><History className="h-4 w-4" /> What the chain proves</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Ownership, assignment, identity and document validity are read from the deployed contracts. This dashboard does not use local storage to decide what you own.</p></section></div></TabsContent>
    </Tabs>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={() => setSelected(null)}><div className="w-full max-w-2xl rounded-lg border bg-card p-6" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Asset detail</p><h2 className="mt-1 text-xl font-semibold">#{selected.tokenId} · {assetTypeLabel(selected.assetType)}</h2></div><Button variant="ghost" size="icon" onClick={() => setSelected(null)}><X className="h-4 w-4" /></Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info label="Owner" value={selected.owner} mono /><Info label="Assigned to" value={selected.assignee} mono /><Info label="Status" value={assetStatusLabel(selected.status)} /><Info label="Metadata URI" value={selected.metadataURI} mono /></div><h3 className="mt-6 border-t pt-5 text-sm font-semibold">Ownership history</h3><div className="mt-3 space-y-2">{history.map((event, i) => <div key={`${event.transactionHash}-${i}`} className="flex justify-between gap-3 rounded-md border p-3 text-sm"><span>{event.kind}</span><span className="font-mono text-xs text-muted-foreground">block {event.blockNumber}</span></div>)}</div></div></div>}
  </div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border bg-card p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function Info({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={cn("mt-1 break-all text-sm", mono && "font-mono text-xs")}>{value}</p></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border bg-card p-10 text-center"><Package className="mx-auto h-8 w-8 text-muted-foreground" /><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>; }
